### ISSUE TITLE
menu doesnt show up after text

### ISSUE THREAD

**Issue by MxPy** [MxPy/GMTK-Game-Jam-2024#2]
as tittle says, menu stays hidden after intro finished, i dont know whats is intended behaviour so i leave fix to you @iraszewska

**Comment by iraszewska** [comment]
do you get any errors? I think some object may be not assigned for MenuController in the inspector. I wasn't hard-coding it, because everything still fluctuates. I just checked it on master and it works fine, see if your MenuController looks like that, if not then I'll figure something out:
![controller](https://github.com/user-attachments/assets/a0cc141a-c3b7-458c-9632-0fe906682043)

If by menu you mean buttons then it is intended behaviour, they are supposed to be hidden for now when I'm working on sliding panel

**Comment by iraszewska** [comment]
Found a fix to it, but I'm not sure if we need to go that far, but I can create customs taggs for title and panel and then hardcode showing them after EndIntro() fun

**Comment by MxPy** [comment]
Menu works fine in release
